steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '--build-arg', 'OPENAI_API_KEY=${_OPENAI_API_KEY}',
         '-t', 'gcr.io/$PROJECT_ID/vinyl-app', 
         '.']
  secretEnv: ['_OPENAI_API_KEY']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
    env: '_OPENAI_API_KEY'